### ISSUE TITLE
Reduce dependencies

### ISSUE THREAD

**Issue by jeremyhaile** [Zeumo/datetime-picker#1]
The number of dependencies on this project are too much. In particular, we do not want to add lodash and handlebars into our project just for a date time picker.

Are there any plans to reduce the number of dependencies so that you can get wider adoption?

**Comment by nicinabox** [comment]
I only see 3 methods being used: `extend`, `bind`, and `noop`. Handlebars was a dev convenience, but that would be easy to change I think.

**Comment by nicinabox** [comment]
I think it's safe to assume jquery will be available though?

**Comment by jeremyhaile** [comment]
Yes, I believe date picker already depends on moment right?  And it's a jquery plugin.  So those dependencies are fine. The only ones we didn't already have in our project were lodash and handlebars.  (we use underscore and hamlcoffee, so including those would be wasteful for us)

**Comment by nicinabox** [comment]
If you're using underscore these methods are already compatible.

**Comment by jeremyhaile** [comment]
@nicinabox any progress on removing dependencies?  Just curious since we're trying to decide between using a different datepicker or possibly forking this one to remove the dependencies.  But we'd rather just adopt this one if you guys were going to be removing some!

**Comment by nicinabox** [comment]
Check out the `trim-dependencies` branch. I've already removed lodash, but haven't yet attempted handlebars.

You're welcome to work off that branch and send a PR if you get to it before me.

**Comment by nicinabox** [comment]
I'd like to use some sort of "templating" so the markup can live in it's own file, but can compile down to something that doesn't need extra deps to parse. Maybe [something like this](http://mir.aculo.us/2011/03/09/little-helpers-a-tweet-sized-javascript-templating-engine/) would work?

**Comment by jeremyhaile** [comment]
I like that - does the job but small enough that it doesn't add much extra JS. And doesn't add a dependency for a small amount of templating.

**Comment by nicinabox** [comment]
@jeremyhaile If you want to have a look now I think it should be working without handlebars :)

**Comment by jeremyhaile** [comment]
@nicinabox Thanks - we'll give it a try!

**Comment by nicinabox** [comment]
@jeremyhaile have you been able to test this out? I'm ready to merge this if it's good.

**Comment by jeremyhaile** [comment]
@nicinabox we're working on this today, but don't have it integrated quite yet!

**Comment by nicinabox** [comment]
These changes have been merged to master. Feel free to open an issue if you have any trouble.
