### ISSUE TITLE
How to manually set date time using the plugin?

### ISSUE THREAD

**Issue by Elavarasanlee** [Zeumo/datetime-picker#3]
Hi Guys,
   Thanks for creating this plugin. It's really helping me. I am just trying to figure out how to manually set date and time using this plugin. A timely help would really help me a lot.

Thank You,
Lee

**Comment by nicinabox** [comment]
@Elavarasanlee The picker will reflect the value of the input. If the input has no value the date will default to today and the time to the next hour.
